sudo: required

language: cpp
compiler:
    - gcc

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - boost-latest
        packages:
            - gcc-5
            - g++-5

        packages:
            - libboost1.55-system-dev
            - gcc-5
            - g++-5

        coverity_scan:
            name: AnuRandom
            version: 1.0
            description: anu random data downloader
            notification_email: michalkielan6@gmail.com


before_script:
    - sudo ln -s /usr/lib/libboost_system.* /usr/lib/libboost_system.so

script: make all

branch_pattern: master
