sudo: required
dist: trusty

language: cpp

compiler: g++-5

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - boost-latest
        packages:
            - libboost1.55-all-dev
            - gcc-5
            - g++-5
            - clang-3.6


before_script:
    - sudo ln -s /usr/lib/libboost_system.* /usr/lib/libboost_system.so

env: GCC_VERSION=5 CPP=14 LIBCXX=Off

addons: *gcc5

script: make all

